spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://${POSTGRESHOST}:5432/${POSTGRESDATABASE}?sslmode=require
spring.datasource.username=${POSTGRESUSER}
spring.datasource.password=${POSTGRESPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver